# Generated by Django 5.0.7 on 2024-07-11 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=255, verbose_name='Name of product')),
                ('quantity', models.IntegerField(default=0)),
            ],
        ),
    ]
