# Generated by Django 5.0.7 on 2024-07-12 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='product_quantity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App.company'),
        ),
    ]
